# Generated by Django 4.2.23 on 2025-08-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("full_name", models.TextField(blank=True)),
                ("link", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("programme", models.CharField(blank=True, max_length=255)),
                ("modality", models.CharField(blank=True, max_length=255)),
                ("obs_type", models.CharField(blank=True, max_length=255)),
                ("protocol", models.CharField(blank=True, max_length=255)),
                ("platform", models.CharField(blank=True, max_length=255)),
                ("workflow", models.CharField(blank=True, max_length=255)),
                ("cn_type", models.CharField(blank=True, max_length=255)),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("cancer_type", models.CharField(blank=True, max_length=255)),
                ("cancer_type_full_name", models.TextField(blank=True)),
                ("sample_num", models.PositiveIntegerField(blank=True, null=True)),
                ("cell_num", models.PositiveIntegerField(blank=True, null=True)),
                ("spot_num", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
