# Generated by Django 4.2.23 on 2025-08-09 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkSampleMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_id", models.CharField(max_length=255, unique=True)),
                ("disease_type", models.CharField(blank=True, max_length=255)),
                ("primary_site", models.CharField(blank=True, max_length=255)),
                ("tumor_stage", models.CharField(blank=True, max_length=100)),
                ("tumor_grade", models.CharField(blank=True, max_length=100)),
                ("ethnicity", models.CharField(blank=True, max_length=255)),
                ("race", models.CharField(blank=True, max_length=255)),
                ("gender", models.CharField(blank=True, max_length=20)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("pfs", models.IntegerField(blank=True, null=True)),
                ("days_to_death", models.IntegerField(blank=True, null=True)),
                ("pfs_status", models.CharField(blank=True, max_length=100)),
                ("vital_status", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="database.dataset",
                    ),
                ),
            ],
        ),
    ]
