# Generated by Django 4.2.23 on 2025-08-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0002_bulksamplemetadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulksamplemetadata",
            name="sample_id",
            field=models.CharField(max_length=255),
        ),
    ]
