# Generated by Django 4.2.23 on 2025-10-05 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasicAnnotationTask",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("S", "Success"),
                            ("P", "Pending"),
                            ("F", "Failed"),
                            ("R", "Running"),
                        ],
                        default="P",
                    ),
                ),
                ("create_time", models.DateTimeField()),
                ("finish_time", models.DateTimeField(blank=True, null=True)),
                ("k", models.IntegerField(blank=True, default=10, null=True)),
                (
                    "ref",
                    models.CharField(
                        choices=[("hg19", "Hg19"), ("hg38", "Hg38")], default="hg38"
                    ),
                ),
                (
                    "obs_type",
                    models.CharField(
                        choices=[
                            ("sample", "Bulk Sequencing"),
                            ("cell", "Single-cell Sequencing"),
                            ("spot", "Spatial Transcriptomics"),
                        ],
                        default="sample",
                    ),
                ),
                (
                    "window_type",
                    models.CharField(
                        choices=[("bin", "Bin"), ("gene", "Gene")], default="bin"
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[("int", "Integer"), ("log", "Log")], default="int"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecurrentCNATask",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("S", "Success"),
                            ("P", "Pending"),
                            ("F", "Failed"),
                            ("R", "Running"),
                        ],
                        default="P",
                    ),
                ),
                ("create_time", models.DateTimeField()),
                ("finish_time", models.DateTimeField(blank=True, null=True)),
                (
                    "ref",
                    models.CharField(
                        choices=[("hg19", "Hg19"), ("hg38", "Hg38")], default="hg38"
                    ),
                ),
                (
                    "obs_type",
                    models.CharField(
                        choices=[
                            ("sample", "Bulk Sequencing"),
                            ("cell", "Single-cell Sequencing"),
                            ("spot", "Spatial Transcriptomics"),
                        ],
                        default="sample",
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[("int", "Integer"), ("log", "Log")], default="int"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
